name: Regen Docs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  RegenDocs:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - name: Checkout
        uses: actions/checkout@v3

      - name: CloneWiki
        uses: actions/checkout@v3
        with:
          repository: jon-gilbert/openscad_attachable_text3d.wiki
          path: openscad_attachable_text3d.wiki

      - name: APT update
        run: sudo apt update

      - name: Install Required Libraries
        run: sudo apt-get install python3-pip python3-dev python3-setuptools python3-pil gifsicle libfuse2 git

      - name: Install openscad-docsgen
        run: sudo pip3 install openscad-docsgen

      - name: Install OpenSCAD
        run: |
          cd $GITHUB_WORKSPACE
          wget https://files.openscad.org/OpenSCAD-2021.01-x86_64.AppImage
          sudo mv OpenSCAD-2021.01*-x86_64.AppImage /usr/local/bin/openscad
          sudo chmod +x /usr/local/bin/openscad

      - name: Install BOSL2
        run: git clone https://github.com/BelfrySCAD/BOSL2.git

      - name: Generate Wiki docs
        uses: GabrielBB/xvfb-action@v1.6
        env:
          OPENSCADPATH: ${{ github.workspace }}/..
        with:
          run: openscad-docsgen -f

      - name: Upload docs to wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "openscad_attachable_text3d.wiki"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PAT }}

